const facts = {
  windows7: [
    "You can use the 'shake' feature to minimize all windows except the one you're working on. Just click and hold the title bar of the window you want to keep and shake it.",
    "Pin frequently used programs to the taskbar for quick access. Right-click the program's icon and select 'Pin to taskbar'.",
    "Use Windows Search to quickly find files and programs. Just click the Start button and start typing.",
    "Create a new folder on the desktop by right-clicking and selecting 'New' > 'Folder'.",
    "Use 'God Mode' to access all control panel settings in one place. Create a new folder and name it 'GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}'.",
    "Use the Snipping Tool to capture screenshots. You can find it in the Start Menu.",
    "Pressing Windows Key + P lets you quickly switch between display modes for projectors.",
    "Right-click on the taskbar and select 'Start Task Manager' to manage running applications.",
    "You can burn ISO images directly to a CD or DVD by right-clicking the ISO file and selecting 'Burn disc image'.",
    "Pressing Windows Key + Home minimizes all windows except the active one.",
    "Use the Problem Steps Recorder to capture the steps you take to reproduce a problem. Type 'psr' in the Start Menu search.",
    "You can create custom keyboard shortcuts for your favorite applications.",
    "Use Jump Lists to quickly access recent files for a program. Right-click the program's icon on the taskbar.",
    "Pressing Windows Key + Left Arrow or Right Arrow will snap the current window to the side of the screen.",
    "You can change the size of desktop icons by holding down the Ctrl key and scrolling the mouse wheel.",
    "Use the ' Sticky Notes' application to create virtual sticky notes on your desktop.",
    "You can create a system restore point to revert your computer to a previous state. Search for 'Create a restore point' in the Start Menu.",
    "Pressing Ctrl + Shift + Esc opens the Task Manager directly.",
    "You can customize the notification area (system tray) to hide or show icons.",
    "Use the 'Disk Cleanup' utility to free up space on your hard drive. Search for 'Disk Cleanup' in the Start Menu.",
    "Pinning an item to a Jump List makes it permanently available in that list. Right-click the recent item and select 'Pin to this list'.",
    "Aero Snap can be used to quickly resize windows. Drag a window to the top of the screen to maximize it.",
    "Drag a window to the left or right edge of the screen to make it fill that half of the screen.",
    "Aero Peek lets you see your desktop by hovering over the 'Show Desktop' button at the end of the taskbar.",
    "Clicking the 'Show Desktop' button minimizes all windows.",
    "You can disable Aero effects if you prefer a simpler look or want to improve performance. Right-click the desktop, select 'Personalize', and choose a basic theme.",
    "The Action Center collects and displays alerts from Windows and your applications.",
    "Create a HomeGroup to easily share files and printers with other Windows 7 computers on your network.",
    "Use Windows Media Center to watch and record live TV, play music, and view photos.",
    "Windows Defender provides basic protection against spyware.",
    "The default location for your personal files (Documents, Music, etc.) is in your user folder at C:\\Users\\[YourUsername].",
    "You can change the program that opens a specific file type by right-clicking the file, selecting 'Open with', and choosing a new default.",
    "Libraries allow you to organize files from different locations into a single view.",
    "You can customize the Start Menu by right-clicking the Start button and selecting 'Properties'.",
    "Device Stage provides a central location to manage printers, cameras, and other connected devices.",
    "BitLocker Drive Encryption can protect your entire hard drive from unauthorized access if your computer is lost or stolen.",
    "Parental Controls can help you manage your children's computer use.",
    "Use the 'Calculator' in different modes, like Scientific or Programmer, by clicking the 'View' menu.",
    "The 'Magnifier' tool can enlarge parts of your screen. Press Windows Key and '+' to turn it on.",
    "The On-Screen Keyboard allows you to type without a physical keyboard.",
    "Use 'Remote Desktop Connection' to access another computer over a network.",
    "The 'Resource Monitor' provides a detailed look at how your system is using resources like CPU, memory, and disk.",
    "You can schedule tasks to run automatically using the 'Task Scheduler'.",
    "Create a system repair disc to help you boot your computer if it has a serious error. Search for 'Create a System Repair Disc' in the Start Menu.",
    "The 'Sound Recorder' lets you record audio from a microphone.",
    "Use 'Windows Easy Transfer' to copy your files and settings from an old computer to a new one.",
    "You can adjust your screen resolution by right-clicking the desktop and selecting 'Screen resolution'.",
    "Calibrate your display's color to ensure accurate colors by searching for 'Calibrate display color' in the Start Menu.",
    "The 'Character Map' utility lets you find and insert special characters not on your keyboard.",
    "You can manage your saved network passwords in the 'Credential Manager'.",
    "Enable 'Previous Versions' to restore files that you accidentally deleted or changed. This requires System Restore to be active.",
    "You can add gadgets to your desktop, like a clock or a weather forecast.",
    "Use 'Windows Firewall' to help protect your computer from network threats.",
    "Change your power plan settings to balance performance and energy consumption. Search for 'Power Options' in the Start Menu.",
    "You can add new fonts to your system by placing font files in the C:\\Windows\\Fonts folder.",
    "Check your Windows Experience Index score to see a basic rating of your computer's hardware performance.",
    "The 'Event Viewer' logs important events that happen in Windows, which can be useful for troubleshooting.",
    "Use 'Performance Monitor' to view detailed performance data over time.",
    "You can create a new user account for someone else to use your computer in 'User Accounts' in the Control Panel.",
    "Run a program in compatibility mode if it was designed for an older version of Windows. Right-click the program's executable and go to 'Properties' > 'Compatibility'.",
    "The 'System Configuration' utility (msconfig) lets you change which programs start with Windows.",
    "Pressing Windows Key + Tab activates Aero Flip 3D, a visual way to switch between windows.",
    "You can customize the icons that appear in the notification area.",
    "The 'Math Input Panel' allows you to write math equations with a mouse or stylus, which can then be inserted into documents.",
    "Use 'Windows Update' to keep your system secure and up-to-date.",
    "You can create a keyboard shortcut to launch any program. Right-click its shortcut, go to 'Properties', and set a 'Shortcut key'.",
    "The 'Connect to a Projector' wizard makes it easy to set up for a presentation.",
    "You can view and manage your installed programs in 'Programs and Features' in the Control Panel.",
    "Use 'Location and Other Sensors' to allow programs to use your location, if your hardware supports it.",
    "You can back up your files to an external drive or network location using 'Backup and Restore'.",
    "The 'Sync Center' allows you to sync files with network folders to access them offline.",
    "You can change the date and time by clicking the clock in the taskbar.",
    "Adjust your mouse settings, like pointer speed and double-click speed, in the 'Mouse' section of the Control Panel.",
    "The 'Ease of Access Center' provides settings to make Windows easier to use for people with disabilities.",
    "You can change your desktop background by right-clicking the desktop and selecting 'Personalize'.",
    "Add a screen saver to display an animation when your computer is idle.",
    "You can change the system sounds for different events, like logging in or getting a notification.",
    "The 'Indexing Options' control which files are included in Windows Search for faster searching.",
    "Use 'Troubleshooting' in the Control Panel to automatically diagnose and fix common problems.",
    "You can view detailed information about your computer's hardware and software in 'System Information'.",
    "The 'Services' tool lets you manage the background services that run on your computer.",
    "You can partition your hard drive using the 'Disk Management' tool.",
    "The 'Windows Memory Diagnostic' tool can check your computer's RAM for errors.",
    "You can change the language used by Windows for menus, dialog boxes, and other text.",
    "Use 'Tablet PC Settings' to configure settings for a stylus or touch screen.",
    "The 'Speech Recognition' feature allows you to control your computer with your voice.",
    "You can defragment your hard drive to improve performance. Search for 'Disk Defragmenter'.",
    "The 'iSCSI Initiator' can be used to connect to external storage arrays over a network.",
    "You can manage your home network settings in the 'Network and Sharing Center'.",
    "The 'Phone and Modem' options are used to configure dial-up modems.",
    "Use the 'Remote Assistance' feature to allow someone to help you with a computer problem remotely.",
    "You can create a Virtual Private Network (VPN) connection to connect to a private network over the internet.",
    "The 'Text Services and Input Languages' settings allow you to add and manage different keyboard layouts.",
    "You can change the default web browser, email client, and other default programs in 'Default Programs'.",
    "Use the 'Folder Options' to customize how files and folders are displayed in Windows Explorer.",
    "You can set your computer to go to sleep or hibernate after a period of inactivity to save power.",
    "The 'Color Management' settings help ensure that colors are displayed consistently across different devices."
  ],
  windows8: [
    "You can bring back the Start button by updating to Windows 8.1.",
    "The Charms bar can be accessed by moving your mouse to the top or bottom right corners of the screen.",
    "Pressing Windows Key + X opens the Power User menu with quick access to system tools.",
    "You can close a Metro app by dragging it from the top of the screen to the bottom.",
    "Pressing Windows Key + C opens the Charms bar.",
    "You can view all your apps by clicking the down arrow on the Start screen.",
    "Search for anything on your computer or the web by opening the Charms bar and clicking 'Search'.",
    "You can snap two apps side-by-side to multitask.",
    "Use the 'PC Settings' to configure your computer. It's different from the Control Panel.",
    "You can create a picture password to log in to your computer.",
    "The Task Manager in Windows 8 has been redesigned to be more user-friendly.",
    "Pressing Windows Key + D will always take you to the desktop.",
    "You can right-click on a tile on the Start screen to resize, unpin, or uninstall it.",
    "Pressing Windows Key + Tab opens the app switcher for Metro apps.",
    "You can create a custom 'Apps' view on the Start screen to organize your applications.",
    "The 'File History' feature can be used to automatically back up your files.",
    "You can refresh or reset your PC to its factory settings without losing your files.",
    "Pressing Windows Key + I opens the Settings charm.",
    "You can use the 'Smart Screen' filter to protect your computer from malicious websites and applications.",
    "The Windows Store is where you can download new apps for your computer.",
    "Pin your favorite apps to the Start screen for easy access. Right-click an app and select 'Pin to Start'.",
    "You can group tiles on the Start screen to organize them. Drag a tile to an empty space to create a new group.",
    "Name your tile groups by right-clicking the Start screen and selecting 'Customize'.",
    "Windows 8 introduced the concept of 'live tiles', which can display real-time information.",
    "The 'Share' charm lets you share content from the current app with other apps or services.",
    "The 'Devices' charm is used to send content to connected devices, like printers or TVs.",
    "You can customize the lock screen with your own pictures and choose which apps show notifications.",
    "Pressing Ctrl + Tab on the Start screen lets you view a list of all installed apps.",
    "Windows To Go allows you to create a bootable Windows 8 USB drive that you can use on any computer.",
    "Secure Boot is a feature that helps prevent malicious software from loading when your PC starts up.",
    "You can sign in to Windows 8 with a Microsoft account to sync your settings and files across devices.",
    "The ribbon interface in File Explorer provides quick access to common commands.",
    "Storage Spaces lets you group drives together into a 'storage pool', which can help protect your data from drive failure.",
    "The 'Family Safety' feature helps you monitor and manage your children's PC use.",
    "Windows 8 has built-in antivirus protection with Windows Defender.",
    "The 'Narrator' can read text on the screen aloud.",
    "The 'Ease of Access Center' has tools to make Windows 8 easier to use.",
    "You can use the 'Disk Defragmenter' to optimize your hard drive's performance.",
    "The 'System Restore' feature can help you undo system changes if something goes wrong.",
    "You can create a 'recovery drive' to troubleshoot and fix problems with your PC.",
    "The 'Resource Monitor' shows you how your computer is using its resources in detail.",
    "You can use the 'Performance Monitor' to track your computer's performance over time.",
    "The 'Event Viewer' logs important events that happen in Windows.",
    "The 'Task Scheduler' can be used to run tasks automatically.",
    "The 'Services' tool lets you manage the background services that run on your computer.",
    "The 'System Configuration' utility (msconfig) lets you change startup settings.",
    "The 'Windows Memory Diagnostic' tool can check your computer's RAM for errors.",
    "The 'Disk Management' tool lets you partition and manage your hard drives.",
    "The 'iSCSI Initiator' can be used to connect to external storage arrays over a network.",
    "The 'Windows Firewall' helps protect your computer from network threats.",
    "You can create a VPN connection to connect to a private network over the internet.",
    "The 'Phone and Modem' options are used to configure dial-up modems.",
    "The 'Credential Manager' stores your passwords for websites, apps, and networks.",
    "The 'Indexing Options' control which files are included in Windows Search.",
    "The 'Folder Options' let you customize how files and folders are displayed.",
    "The 'Power Options' let you manage your computer's power consumption.",
    "The 'Sync Center' lets you sync files with network folders for offline access.",
    "You can change the date and time by clicking the clock in the taskbar.",
    "The 'Region' settings in the Control Panel let you change your country and language preferences.",
    "You can add and manage user accounts in the 'User Accounts' section of the Control Panel.",
    "The 'Default Programs' settings let you choose which apps to use for different file types and protocols.",
    "The 'Programs and Features' tool lets you uninstall or change programs.",
    "You can back up your files using 'File History' or 'Windows Backup'.",
    "The 'Troubleshooting' tool can help you diagnose and fix common problems.",
    "The 'System' window in the Control Panel shows you basic information about your computer.",
    "You can change your screen resolution in the 'Display' settings.",
    "The 'Personalization' settings let you change your desktop background, colors, and sounds.",
    "You can set up a screen saver to display when your computer is idle.",
    "The 'Mouse' settings let you customize your mouse pointer, speed, and other options.",
    "The 'Keyboard' settings let you change your keyboard layout and other options.",
    "The 'Sound' settings let you manage your audio devices and system sounds.",
    "The 'Speech Recognition' feature lets you control your computer with your voice.",
    "The 'Tablet PC Settings' are for configuring a stylus or touch screen.",
    "The 'Color Management' settings help ensure accurate color reproduction.",
    "You can manage your network connections in the 'Network and Sharing Center'.",
    "The 'HomeGroup' feature lets you share files and printers with other computers on your home network.",
    "The 'RemoteApp and Desktop Connections' feature lets you access programs and desktops on a remote server.",
    "You can manage your BitLocker Drive Encryption settings in the Control Panel.",
    "The 'Administrative Tools' folder contains tools for system administrators and advanced users.",
    "The 'Device Manager' lets you view and manage the hardware devices installed in your computer.",
    "The 'Print Management' tool lets you manage printers and print servers.",
    "The 'Component Services' tool is for developers and administrators to manage COM components.",
    "The 'Data Sources (ODBC)' tool is for connecting to databases.",
    "The 'Computer Management' console provides access to a collection of administrative tools.",
    "The 'Local Security Policy' editor lets you configure security settings for your computer.",
    "The 'Windows PowerShell' is a powerful command-line shell and scripting language.",
    "The 'Command Prompt' provides a traditional command-line interface.",
    "You can use 'Hyper-V' to create and run virtual machines.",
    "The 'Windows Mobility Center' provides quick access to settings for mobile computers.",
    "You can use 'Windows Media Player' to play music and videos.",
    "The 'Windows Journal' is a note-taking application for Tablet PCs.",
    "The 'Sticky Notes' app lets you create virtual sticky notes on your desktop.",
    "The 'Snipping Tool' can be used to capture screenshots.",
    "The 'Calculator' has standard, scientific, programmer, and statistics modes.",
    "The 'Sound Recorder' can be used to record audio.",
    "The 'Character Map' lets you insert special characters into your documents.",
    "The 'Math Input Panel' can recognize handwritten math equations.",
    "You can use 'Windows Fax and Scan' to send and receive faxes and scan documents."
  ],
  windows10: [
    "Use the Task View to see all your open windows and create virtual desktops. Click the Task View button on the taskbar or press Windows Key + Tab.",
    "Cortana is your personal digital assistant. You can ask her questions, set reminders, and more.",
    "The Action Center is where you can find your notifications and quick access to settings. Press Windows Key + A to open it.",
    "You can use 'Night light' to reduce blue light and help you sleep better. Go to Settings > System > Display.",
    "Pressing Windows Key + G opens the Game Bar, where you can record gameplay and take screenshots.",
    "You can use 'Focus assist' to block notifications and distractions. Go to Settings > System > Focus assist.",
    "The 'Timeline' feature shows you a history of your activities on your computer. Press Windows Key + Tab to access it.",
    "You can use 'Storage Sense' to automatically free up disk space. Go to Settings > System > Storage.",
    "Pressing Windows Key + . (period) opens the emoji keyboard.",
    "You can use 'Windows Hello' to sign in with your face or fingerprint.",
    "The 'Your Phone' app lets you connect your Android phone to your PC to access photos, messages, and more.",
    "You can use 'Cloud Clipboard' to copy and paste across your devices. Go to Settings > System > Clipboard.",
    "Pressing Windows Key + Shift + S opens the new Snipping Tool to capture screenshots.",
    "You can use 'Dark Mode' to change the look of your apps and the operating system. Go to Settings > Personalization > Colors.",
    "The 'Photos' app can be used to organize, edit, and create videos from your photos.",
    "You can use 'Windows Ink Workspace' to draw, take notes, and more. Click the pen icon in the taskbar.",
    "Pressing Windows Key + L locks your computer.",
    "You can use 'Dynamic Lock' to automatically lock your PC when you're away. Go to Settings > Accounts > Sign-in options.",
    "The 'Microsoft Store' is where you can download apps, games, and more.",
    "You can use 'Windows Defender' to protect your computer from viruses and malware.",
    "The Start Menu in Windows 10 combines the classic Start Menu with Live Tiles from Windows 8.",
    "You can resize the Start Menu by dragging its edges.",
    "Right-click on a tile to resize, unpin, or turn its live updates off.",
    "Create groups of tiles by dragging them to an empty space and giving the group a name.",
    "You can uninstall most apps by right-clicking their entry in the Start Menu and selecting 'Uninstall'.",
    "Switch between virtual desktops by pressing Ctrl + Windows Key + Left/Right Arrow.",
    "Close a virtual desktop by pressing Ctrl + Windows Key + F4.",
    "Move an open window to another virtual desktop by dragging it in Task View.",
    "The Action Center can be customized to show the quick actions you use most.",
    "You can project your screen to a wireless display by pressing Windows Key + P and selecting 'Connect to a wireless display'.",
    "Battery Saver mode can extend your laptop's battery life by limiting background activity.",
    "You can see which apps are using the most battery in Settings > System > Battery.",
    "The Maps app provides turn-by-turn directions, traffic information, and lets you download maps for offline use.",
    "The Groove Music app can play music from your local library and from OneDrive.",
    "Microsoft Edge is the default web browser, featuring a reading mode and the ability to draw on web pages.",
    "You can set 'quiet hours' for Focus Assist to automatically turn on during specific times.",
    "The 'Game Mode' can improve gaming performance by dedicating more system resources to your game.",
    "You can record video clips and screenshots of your games with the Game Bar.",
    "The 'People' app integrates with your email and calendar to keep your contacts organized.",
    "You can pin your favorite people to the taskbar for quick access to their contact information.",
    "The 'Mail and Calendar' apps are built-in for managing your email and schedule.",
    "You can set a data limit to help you stay under your internet data cap in Settings > Network & Internet > Data usage.",
    "Find My Device can help you locate your Windows 10 device if it's lost or stolen.",
    "You can use a PIN or a picture password for a faster way to sign in.",
    "Windows Update can be scheduled to restart your computer at a time that's convenient for you.",
    "You can defer feature updates for several months if you don't want to install them right away.",
    "The 'Narrator' can read text on the screen aloud and describe events.",
    "The 'Magnifier' can enlarge all or part of your screen.",
    "High contrast themes can make the screen easier to see for people with visual impairments.",
    "The On-Screen Keyboard can be used to type with a mouse or other pointing device.",
    "Sticky Keys, Filter Keys, and Toggle Keys are accessibility features for people who have difficulty using a standard keyboard.",
    "You can control the mouse cursor with the numeric keypad.",
    "The 'Recovery Drive' creator can help you make a bootable USB drive to troubleshoot problems.",
    "You can reset your PC to its factory settings, with the option to keep your personal files.",
    "The 'System Restore' feature can take your PC back to an earlier point in time.",
    "The 'Resource Monitor' provides a detailed view of your system's resource usage.",
    "The 'Performance Monitor' can be used to analyze your system's performance over time.",
    "The 'Event Viewer' logs system events, which can be helpful for troubleshooting.",
    "The 'Task Scheduler' can be used to automate tasks.",
    "The 'Services' manager lets you control background services.",
    "The 'System Configuration' utility (msconfig) helps you manage startup programs.",
    "The 'Windows Memory Diagnostic' tool can test your RAM for errors.",
    "The 'Disk Management' tool allows you to manage your hard drives and partitions.",
    "The 'iSCSI Initiator' is for connecting to storage area networks.",
    "The 'Windows Firewall' helps protect your PC from unauthorized access.",
    "You can create a VPN connection to access a private network securely.",
    "The 'Credential Manager' stores your login information for websites and other resources.",
    "The 'Indexing Options' control how Windows Search indexes your files.",
    "The 'Folder Options' allow you to customize the appearance and behavior of File Explorer.",
    "The 'Power Options' let you fine-tune your PC's power usage.",
    "The 'Sync Center' is for syncing files with network servers.",
    "The 'Region' settings allow you to customize formats for dates, times, and currency.",
    "You can manage user accounts for your family or other users in the 'User Accounts' settings.",
    "The 'Default apps' settings let you choose your preferred web browser, email client, etc.",
    "You can manage installed apps in 'Apps & features'.",
    "The 'Troubleshooting' section in Settings can automatically fix some common problems.",
    "The 'System' settings show you basic information about your PC.",
    "You can customize your display's scaling, resolution, and orientation.",
    "The 'Personalization' settings let you change your background, colors, and themes.",
    "You can set up a slideshow as your lock screen background.",
    "The 'Mouse' settings let you configure your mouse for right or left-handed use.",
    "The 'Keyboard' settings let you adjust your keyboard's repeat rate and other options.",
    "The 'Sound' settings let you manage your audio devices.",
    "The 'Speech' settings are for configuring text-to-speech and speech recognition.",
    "The 'Tablet mode' makes Windows 10 more touch-friendly on convertible devices.",
    "The 'Color Management' settings help you get accurate colors on your display.",
    "The 'Network and Sharing Center' is for managing your network connections.",
    "The 'HomeGroup' feature has been removed in newer versions of Windows 10, but file sharing is still available.",
    "You can use 'Remote Desktop' to connect to another computer.",
    "BitLocker can encrypt your drive to protect your data.",
    "The 'Administrative Tools' folder contains advanced tools for managing Windows.",
    "The 'Device Manager' lets you manage your hardware devices.",
    "The 'Print Management' console is for managing printers and print servers.",
    "The 'Component Services' and 'Data Sources (ODBC)' are tools for developers and administrators.",
    "The 'Computer Management' console provides access to many administrative tools.",
    "The 'Local Security Policy' editor is for configuring security settings.",
    "Windows PowerShell is a powerful tool for automating tasks and managing your system.",
    "The Command Prompt is still available for running traditional command-line commands.",
    "Hyper-V allows you to run virtual machines on your PC.",
    "Windows To Go is a feature for creating a bootable Windows 10 USB drive (Enterprise edition).",
    "The 'Windows Mobility Center' is for quick access to settings on laptops and tablets."
  ],
  windows11: [
    "The Start Menu is now centered on the taskbar, but you can move it back to the left in Settings.",
    "Widgets bring you closer to the information you want. Click the Widgets icon on the taskbar to see news, weather, and more.",
    "Snap Layouts and Snap Groups make it easy to organize your windows and multitask. Hover over the maximize button to see the available layouts.",
    "Microsoft Teams is integrated into the taskbar for easy access to chat and video calls.",
    "The Microsoft Store has been redesigned and now includes Android apps.",
    "You can use 'Focus sessions' to help you stay productive. It's part of the Clock app.",
    "The Settings app has been redesigned to be more user-friendly.",
    "You can use 'Voice typing' to dictate text. Press Windows Key + H to start.",
    "The 'Photos' app has a new look and feel, with a redesigned toolbar and a new 'multi-view' feature.",
    "You can use 'Windows Sandbox' to run applications in an isolated environment.",
    "The 'Clipboard history' feature lets you see a list of items you've copied. Press Windows Key + V to access it.",
    "You can use 'Virtual desktops' to create separate workspaces for different tasks. Press Windows Key + Ctrl + D to create a new one.",
    "The 'Game Pass' for PC is a subscription service that gives you access to a library of games.",
    "You can use 'Power Automate' to automate repetitive tasks.",
    "The 'Terminal' app is a new command-line tool for power users.",
    "You can use 'Windows Subsystem for Linux' to run Linux distributions on your Windows machine.",
    "The 'Your Phone' app has been renamed to 'Phone Link'.",
    "You can use 'Nearby sharing' to share files with other Windows devices.",
    "The 'Snipping Tool' has been updated with a new look and new features.",
    "You can use 'Windows Update' to keep your computer up to date with the latest features and security updates.",
    "The right-click context menu is redesigned to be more modern, with a 'Show more options' for the classic view.",
    "Pin your favorite apps to the Start Menu for quick access.",
    "The Start Menu now has a 'Recommended' section that shows your recently opened files and apps.",
    "You can customize the folders that appear on the Start Menu next to the power button in Settings > Personalization > Start.",
    "File Explorer has a new look with a simplified command bar.",
    "Dynamic Refresh Rate can save battery life on supported laptops by automatically adjusting the screen's refresh rate.",
    "Auto HDR can improve the look of games that don't natively support HDR.",
    "DirectStorage can lead to faster game loading times on PCs with NVMe SSDs.",
    "The Chat app (powered by Microsoft Teams) is integrated into the taskbar.",
    "You can create custom emoji combinations with the emoji panel (Windows Key + .).",
    "The Clock app includes Focus Sessions and integrates with Spotify.",
    "Windows 11 can run Android apps, which can be downloaded from the Microsoft Store (via the Amazon Appstore).",
    "You can have multiple desktops for different purposes, and each can have its own wallpaper.",
    "The taskbar can be customized with different alignments and corner icons.",
    "The Quick Settings panel (Windows Key + A) gives you easy access to common settings like Wi-Fi, Bluetooth, and volume.",
    "You can see your notifications by clicking the date and time in the taskbar.",
    "The volume and brightness sliders have been redesigned and are more user-friendly.",
    "You can control your media playback from the Action Center.",
    "The 'Do Not Disturb' mode can silence notifications.",
    "The 'Phone Link' app allows you to sync your Android phone with your PC.",
    "You can use 'Windows Security' to manage your antivirus, firewall, and other security settings.",
    "BitLocker device encryption is available to help protect your data.",
    "Find My Device can help you locate your PC if it's lost.",
    "You can use a PIN, fingerprint, or facial recognition to sign in with Windows Hello.",
    "The 'Parental Controls' are now part of 'Microsoft Family Safety'.",
    "You can change your default web browser in the 'Default apps' settings.",
    "The 'Storage Sense' feature can automatically free up space on your drive.",
    "You can see a detailed breakdown of your storage usage in Settings > System > Storage.",
    "The 'Backup and Restore' feature from Windows 7 is still available, alongside modern backup options.",
    "You can sync your clipboard history across your devices.",
    "The 'Remote Desktop' feature lets you connect to another computer.",
    "You can enable 'developer mode' to get access to advanced features for app development.",
    "The 'Windows Sandbox' provides a temporary, isolated desktop environment to run untrusted software.",
    "The 'Task Manager' has been redesigned with a new look that matches the Windows 11 design.",
    "You can enable 'Efficiency mode' in the Task Manager to limit the resources an app can use.",
    "The 'Resource Monitor' is still available for detailed performance monitoring.",
    "The 'Performance Monitor' can be used to track system performance over time.",
    "The 'Event Viewer' logs system events for troubleshooting.",
    "The 'Task Scheduler' can automate tasks.",
    "The 'Services' manager is used to control background services.",
    "The 'System Configuration' utility (msconfig) is still available for managing startup processes.",
    "The 'Windows Memory Diagnostic' tool can check your RAM for problems.",
    "The 'Disk Management' tool is for managing your hard drives and partitions.",
    "The 'iSCSI Initiator' is for connecting to network storage.",
    "The 'Windows Firewall' helps protect your PC.",
    "You can create and manage VPN connections in the Settings app.",
    "The 'Credential Manager' stores your passwords.",
    "The 'Indexing Options' control what gets indexed for Windows Search.",
    "The 'Folder Options' in File Explorer let you customize its appearance and behavior.",
    "The 'Power & battery' settings let you manage your PC's power consumption.",
    "The 'Sync Center' is for syncing files with network locations.",
    "The 'Region & language' settings allow you to customize your PC's localization.",
    "You can manage user accounts in the 'Accounts' section of Settings.",
    "The 'Apps & features' section is where you can manage your installed applications.",
    "The 'Troubleshoot' settings can automatically resolve common issues.",
    "The 'System' settings show you information about your PC's hardware and Windows version.",
    "You can customize your display's scaling, resolution, and refresh rate.",
    "The 'Personalization' settings are where you can change your theme, background, and colors.",
    "You can set up a custom lock screen with your own photos.",
    "The 'Mouse' settings let you configure your mouse pointer and other options.",
    "The 'Keyboard' settings are for customizing your keyboard layout and behavior.",
    "The 'Sound' settings let you manage your audio devices and volume.",
    "The 'Speech' settings are for text-to-speech and voice recognition.",
    "The 'Gaming' section in Settings has options for the Game Bar, captures, and Game Mode.",
    "The 'Color Management' settings help you get accurate colors.",
    "The 'Network & internet' settings are for managing your Wi-Fi, Ethernet, and other network connections.",
    "You can use 'Remote Assistance' to get help from or provide help to another user.",
    "The 'Administrative Tools' folder contains advanced management tools.",
    "The 'Device Manager' is for managing your hardware.",
    "The 'Print Management' console helps you manage printers.",
    "The 'Component Services' and 'Data Sources (ODBC)' are tools for developers.",
    "The 'Computer Management' console consolidates many administrative tools.",
    "The 'Local Security Policy' editor is for advanced security configuration.",
    "The 'Windows Terminal' is the new default command-line interface, which can host PowerShell and Command Prompt in tabs.",
    "Hyper-V is available for running virtual machines.",
    "The 'Windows Mobility Center' provides quick access to settings on mobile devices.",
    "Windows Media Player has been updated with a new look in Windows 11."
  ],
  macos: [
    "Press Command + Space to open Spotlight search, your go-to for finding anything on your Mac.",
    "Capture a specific area of your screen with Command + Shift + 4.",
    "Use Mission Control (F3) to get a bird's-eye view of all your open windows, desktops, and full-screen apps.",
    "Force-click a word to quickly look up its definition or get more information.",
    "Switch between open applications seamlessly with Command + Tab.",
    "Take a screenshot of your entire screen with Command + Shift + 3.",
    "Quickly preview any file by selecting it and pressing the Spacebar (Quick Look).",
    "Merge multiple Finder windows into one with tabs by going to Window > Merge All Windows.",
    "Use Stacks to automatically organize files on your desktop. Right-click the desktop and choose 'Use Stacks'.",
    "Press Command + Control + Q to instantly lock your screen.",
    "In Safari, press Command + L to instantly jump to the address bar.",
    "Use Command + Option + Esc to open the Force Quit Applications window if an app becomes unresponsive.",
    "Create a new desktop space by entering Mission Control and clicking the '+' in the top-right corner.",
    "Rename a file by selecting it and pressing the Enter key.",
    "In Finder, use Command + Up Arrow to go to the parent folder.",
    "Show or hide the Dock with Command + Option + D.",
    "Instantly create a new folder with selected files by right-clicking and choosing 'New Folder with Selection'.",
    "Use Command + Comma (,) to open the preferences for the active application.",
    "In a text field, use Command + Control + Space to bring up the Character Viewer for emojis and symbols.",
    "Quickly convert a file to PDF from the Print menu. Click the PDF dropdown and choose 'Save as PDF'.",
    "Hot Corners can be set up to trigger actions like starting a screensaver or showing the desktop when you move your mouse to a corner of the screen.",
    "AirDrop allows you to wirelessly share files between Apple devices.",
    "Handoff lets you start work on one Apple device and pick it up on another.",
    "Continuity Camera allows you to use your iPhone's camera to take a picture or scan a document directly into a Mac app.",
    "Universal Clipboard lets you copy content on one Apple device and paste it on another.",
    "The Notification Center can be customized to show the widgets you find most useful.",
    "You can use Siri to perform tasks, get answers, and find files on your Mac.",
    "The Dock can be customized with your favorite apps, and you can change its size and position.",
    "You can use multiple desktops with Mission Control to organize your workspaces.",
    "The App Store is the place to find and download new apps for your Mac.",
    "You can use 'Screen Time' to monitor your usage and set limits for yourself or your children.",
    "The 'Keychain Access' app securely stores your passwords and other sensitive information.",
    "FileVault encrypts your entire Mac startup disk to protect your data.",
    "You can use 'Find My' to locate your Mac if it's lost or stolen.",
    "The 'Gatekeeper' feature helps protect your Mac from malicious software.",
    "You can use 'Time Machine' to back up your entire Mac to an external drive.",
    "The 'Disk Utility' can be used to manage your hard drives and partitions, and to repair disk problems.",
    "The 'Activity Monitor' shows you how your Mac's resources are being used.",
    "You can use the 'Console' app to view detailed log messages, which can be helpful for troubleshooting.",
    "The 'Terminal' provides a command-line interface for advanced users.",
    "You can create custom keyboard shortcuts for your favorite commands in System Settings.",
    "The 'Automator' app lets you create custom workflows to automate repetitive tasks.",
    "You can use 'Shortcuts' to create powerful automations for your Mac and iOS devices.",
    "The 'TextEdit' app is a simple word processor that comes with macOS.",
    "The 'Preview' app can be used to view and edit images and PDFs.",
    "The 'Mail' app is a powerful email client.",
    "The 'Calendar' app helps you manage your schedule.",
    "The 'Contacts' app stores your contact information.",
    "The 'Reminders' app helps you keep track of your to-do lists.",
    "The 'Notes' app is a great place to jot down your thoughts.",
    "The 'Photos' app organizes your photo library.",
    "The 'Music' app is for listening to your music library and Apple Music.",
    "The 'Podcasts' app is for listening to your favorite podcasts.",
    "The 'TV' app is for watching movies, TV shows, and Apple TV+.",
    "The 'Books' app is for reading ebooks and audiobooks.",
    "The 'Maps' app provides directions and helps you explore new places.",
    "The 'Safari' web browser is fast and energy-efficient.",
    "You can use 'iMovie' to create and edit videos.",
    "You can use 'GarageBand' to create music.",
    "The 'Pages', 'Numbers', and 'Keynote' apps are Apple's productivity suite for documents, spreadsheets, and presentations.",
    "You can use 'FaceTime' to make video and audio calls.",
    "The 'Messages' app lets you send text messages, photos, and more.",
    "The 'Voice Memos' app lets you record audio notes.",
    "The 'Stocks' app helps you track the stock market.",
    "The 'News' app provides personalized news from top sources.",
    "The 'Home' app lets you control your smart home devices.",
    "The 'Calculator' app has basic, scientific, and programmer modes.",
    "The 'Dictionary' app lets you look up definitions and synonyms.",
    "The 'Font Book' app helps you manage your fonts.",
    "The 'Image Capture' app can be used to transfer photos from a camera or scanner.",
    "The 'Migration Assistant' can help you transfer your data from an old computer to a new one.",
    "The 'Screenshot' app provides a variety of options for capturing your screen.",
    "The 'Stickies' app lets you create virtual sticky notes.",
    "The 'System Information' app provides detailed information about your Mac's hardware and software.",
    "You can use 'Boot Camp' to install and run Windows on your Mac (Intel-based Macs only).",
    "You can change the system language and region in 'Language & Region' settings.",
    "The 'Accessibility' settings provide a wide range of options to make macOS easier to use.",
    "You can customize your trackpad and mouse gestures in System Settings.",
    "The 'Displays' settings let you manage your screen resolution and arrangement.",
    "The 'Sound' settings let you manage your audio input and output devices.",
    "The 'Users & Groups' settings let you manage user accounts.",
    "The 'Startup Disk' settings let you choose which disk to use to start up your Mac.",
    "You can set a firmware password to prevent your Mac from starting up from an unauthorized disk.",
    "You can use 'Target Disk Mode' to use your Mac as an external hard drive for another Mac.",
    "The 'Recovery Mode' can be used to troubleshoot and repair your Mac.",
    "You can reinstall macOS from Recovery Mode.",
    "The 'Safe Mode' can help you troubleshoot problems that might be caused by software that loads when your Mac starts up.",
    "You can create a 'guest user' account for temporary users.",
    "You can set up a 'shared' folder to share files with other users on your Mac.",
    "You can use the 'Firewall' to protect your Mac from network threats.",
    "The 'Privacy & Security' settings let you control which apps have access to your location, contacts, and other private data.",
    "You can use 'iCloud' to sync your files, photos, and other data across your Apple devices.",
    "You can use 'iCloud Drive' to store your files in the cloud.",
    "You can use 'iCloud Keychain' to sync your passwords and credit card information.",
    "You can use 'iCloud Photos' to store your entire photo library in the cloud.",
    "You can use 'Sidecar' to use your iPad as a second display for your Mac."
  ],
  linux: [
    "The 'sudo' command stands for 'superuser do', allowing you to run commands with administrative privileges.",
    "Use the 'man' command followed by another command's name to view its manual page (e.g., 'man ls').",
    "The 'ls' command lists files and directories. Use 'ls -l' for a detailed list and 'ls -a' to show hidden files.",
    "Navigate between directories with the 'cd' command. Use 'cd ..' to go up one level.",
    "The 'pwd' command prints the current working directory.",
    "Use 'mkdir' to create a new directory and 'rmdir' to remove an empty one.",
    "Pressing Tab in the terminal will autocomplete commands, filenames, and directory names.",
    "Use 'grep' to search for specific text within files. For example, 'grep 'hello' file.txt'.",
    "The 'top' command displays a real-time view of running processes and system resource usage.",
    "Use 'chmod' to change the permissions of a file or directory.",
    "The 'history' command shows a list of your previously executed commands.",
    "You can chain commands together using the pipe '|' symbol. For example, 'ls -l | grep .txt'.",
    "Press Ctrl + C in the terminal to stop the currently running command.",
    "The 'cat' command can be used to display the content of a file in the terminal.",
    "Use the 'find' command to search for files and directories based on various criteria.",
    "The 'tar' command is used to create and extract compressed archive files.",
    "You can create a symbolic link (a shortcut) to a file or directory using the 'ln -s' command.",
    "Use 'df -h' to see the amount of disk space used and available on your filesystems.",
    "The 'ssh' command allows you to securely connect to a remote computer.",
    "You can customize your command prompt by modifying the PS1 environment variable in your '.bashrc' file.",
    "The 'alias' command can create shortcuts for longer commands. Add them to your '.bashrc' to make them permanent.",
    "Use '!!' to repeat the last command you entered.",
    "Press Ctrl + R to search through your command history.",
    "Use '&&' to run a command only if the previous one was successful (e.g., 'make && ./myprogram').",
    "Use '||' to run a command only if the previous one failed.",
    "Redirect the output of a command to a file with the '>' operator (e.g., 'ls > filelist.txt'). Use '>>' to append.",
    "The '/etc/fstab' file defines which filesystems are mounted at boot time.",
    "The '/etc/passwd' file contains user account information.",
    "The 'whoami' command tells you the username of the current user.",
    "The 'uname -a' command displays detailed information about your Linux system kernel.",
    "Use 'lscpu' to see information about your CPU architecture.",
    "Use 'free -h' to see how much memory (RAM) is free and used.",
    "The 'ps aux' command gives you a detailed snapshot of all running processes.",
    "Use the 'kill' command to terminate a process by its ID.",
    "The 'cron' daemon is used to schedule tasks to run at specific times.",
    "Use 'wget' or 'curl' to download files from the internet via the command line.",
    "The 'ping' command is used to test the connectivity between two network hosts.",
    "The 'ifconfig' or 'ip addr' command shows your network interface configuration.",
    "The 'netstat -tuln' command lists all open network ports on your system.",
    "Use 'ssh-keygen' to create a new SSH key pair for secure, passwordless logins.",
    "The 'scp' command allows you to securely copy files between two computers over SSH.",
    "Use 'rsync' for fast, incremental file transfers.",
    "The 'dd' command can be used for low-level copying of data, like creating a disk image.",
    "Use 'lsblk' to list information about all available block devices (like hard drives and USB sticks).",
    "The 'mount' command is used to attach a filesystem to a specific directory.",
    "Use 'fdisk' or 'parted' to manage disk partitions.",
    "The 'du -sh *' command will show you the disk usage of all files and directories in the current location.",
    "The 'which' command tells you the full path of a command (e.g., 'which python').",
    "The 'xargs' command can be used to build and execute command lines from standard input.",
    "Use 'tee' to redirect the output of a command to a file and also see it on the screen.",
    "The 'nohup' command allows you to run a command that will continue to run even after you log out.",
    "You can run a command in the background by adding an '&' at the end.",
    "The 'jobs' command lists all background jobs.",
    "Bring a background job to the foreground with the 'fg' command.",
    "The 'screen' or 'tmux' programs allow you to manage multiple terminal sessions in one window.",
    "The 'Vim' and 'Emacs' are two powerful, classic text editors for the command line.",
    "The 'nano' text editor is a simpler, more user-friendly alternative to Vim and Emacs.",
    "The 'apt', 'yum', or 'dnf' commands are used to install, update, and remove software packages on Debian/Ubuntu and Red Hat/Fedora systems, respectively.",
    "The 'systemctl' command is used to manage services on systems with systemd.",
    "The '/var/log' directory contains log files for the system and various applications.",
    "The 'dmesg' command prints the kernel ring buffer, which can be useful for diagnosing hardware issues.",
    "Use 'lsof' to list all open files and the processes that opened them.",
    "The 'strace' command can be used to trace the system calls made by a program, which is useful for debugging.",
    "The 'ldd' command shows the shared libraries required by a program.",
    "You can create a new user with the 'adduser' command.",
    "The 'su' or 'sudo -i' command can be used to switch to the root user.",
    "The '.bash_history' file in your home directory stores your command history.",
    "The '/tmp' directory is used for temporary files and is often cleared on reboot.",
    "The 'chmod u+x myscript.sh' command makes a shell script executable.",
    "You can run a shell script with './myscript.sh'.",
    "The 'export' command is used to set environment variables.",
    "The 'PATH' environment variable specifies the directories where the shell should look for commands.",
    "The 'echo $?' command will show you the exit code of the last command that was run (0 means success).",
    "You can create a compressed tar archive with 'tar -czvf archive.tar.gz /path/to/directory'.",
    "You can extract a tar archive with 'tar -xzvf archive.tar.gz'.",
    "The 'zip' and 'unzip' commands are used for working with ZIP archives.",
    "The 'gzip' and 'gunzip' commands are used for compressing and decompressing files.",
    "The 'bzip2' command often provides better compression than gzip.",
    "The 'diff' command compares two files and shows the differences.",
    "The 'wc' command can count the lines, words, and characters in a file.",
    "The 'sort' command sorts the lines of a text file.",
    "The 'uniq' command can be used to remove duplicate lines from a sorted file.",
    "The 'head' and 'tail' commands show the beginning and end of a file, respectively.",
    "Use 'tail -f /var/log/syslog' to watch a log file in real-time.",
    "The 'less' command is a powerful tool for viewing large text files.",
    "You can create an empty file with the 'touch' command.",
    "The 'stat' command displays detailed information about a file or filesystem.",
    "The 'ncdu' tool provides an interactive way to analyze disk usage.",
    "The 'htop' command is an interactive process viewer and a more user-friendly alternative to 'top'.",
    "The 'iotop' command can be used to monitor disk I/O usage.",
    "The 'nmap' tool is a powerful network scanner.",
    "The 'tcpdump' command can be used to capture and analyze network traffic.",
    "The 'iptables' or 'ufw' command is used to configure the firewall.",
    "You can see your routing table with the 'route -n' or 'ip route' command.",
    "The 'dig' or 'nslookup' command can be used to query DNS servers.",
    "The 'hostname' command shows or sets the system's host name.",
    "The 'shutdown' command can be used to power off or reboot the system."
  ],
  general: [
    "A kilobyte is 1,024 bytes, not 1,000.",
    "The first computer mouse was made of wood.",
    "The first computer virus was created in 1983.",
    "The first gigabyte hard drive was released in 1980 and weighed 550 pounds.",
    "The @ symbol was originally used in accounting to mean 'at a rate of'."
  ]
};

function getRandomFact(os = 'general') {
  let factPool = [...facts.general];
  if (os !== 'general' && facts[os]) {
    factPool.push(...facts[os]);
  }
  const randomIndex = Math.floor(Math.random() * factPool.length);
  return factPool[randomIndex];
}

module.exports = { getRandomFact };
